// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SD_340_W22SD_Lab4.Data;

#nullable disable

namespace SD_340_W22SD_Lab4.Migrations
{
    [DbContext(typeof(SD_340_W22SD_Lab4Context))]
    [Migration("20220916183524_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SD_340_W22SD_Lab4.Models.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("BicycleAccessible")
                        .HasColumnType("bit");

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<bool>("RampAccessible")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Route");
                });

            modelBuilder.Entity("SD_340_W22SD_Lab4.Models.ScheduledStop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("RouteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ScheduledArrival")
                        .HasColumnType("datetime2");

                    b.Property<int?>("StopId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RouteId");

                    b.HasIndex("StopId");

                    b.ToTable("ScheduledStop");
                });

            modelBuilder.Entity("SD_340_W22SD_Lab4.Models.Stop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Stop");
                });

            modelBuilder.Entity("SD_340_W22SD_Lab4.Models.ScheduledStop", b =>
                {
                    b.HasOne("SD_340_W22SD_Lab4.Models.Route", "Route")
                        .WithMany("ScheduledStops")
                        .HasForeignKey("RouteId");

                    b.HasOne("SD_340_W22SD_Lab4.Models.Stop", "Stop")
                        .WithMany("ScheduledStops")
                        .HasForeignKey("StopId");

                    b.Navigation("Route");

                    b.Navigation("Stop");
                });

            modelBuilder.Entity("SD_340_W22SD_Lab4.Models.Route", b =>
                {
                    b.Navigation("ScheduledStops");
                });

            modelBuilder.Entity("SD_340_W22SD_Lab4.Models.Stop", b =>
                {
                    b.Navigation("ScheduledStops");
                });
#pragma warning restore 612, 618
        }
    }
}
